### ISSUE TITLE
bash completion not initialized

### ISSUE THREAD

**Issue by dougalcorn** [boxen/puppet-bash#1]
The homebrew bash-completion package instructs you to add this to your `~/.bashrc`:

``` bash
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi
```

These instructions get lost when boxen runs. It seems like the a file with those lines should be added to `$BOXEN_ENV_DIR`. If you `include bash::completion` I'd think you'd also want it initialized.

**Comment by rafaelfranca** [comment]
Seems good. Could you open a PR?
